Allow any order of split dump files
Originally, the dump files were assumed to be sorted by ascending
PFN. However, the results can be confusing if split files are
specified in a different order. Instead of improving error
detection, allow to specify the files in any order and sort them
when opening the file set.

This means that the index in the pdmap array no longer corresponds
to the file index under the file.fdset attribute, so this other
index must be stored in the page descriptor map.

Signed-off-by: Petr Tesarik <ptesarik@suse.com>

diff --git a/tests/diskdump-split b/tests/diskdump-split
--- a/tests/diskdump-split
+++ b/tests/diskdump-split
@@ -148,3 +148,23 @@ if [ $rc -ne 0 ]; then
     echo "Attribute check failed" >&2
     exit $rc
 fi
+
+echo "Check combined page map with files out of order"
+./checkattr "$dumpfile.2" "$dumpfile.3" "$dumpfile.1" <<EOF
+file.pagemap = bitmap: 0x1e
+EOF
+rc=$?
+if [ $rc -ne 0 ]; then
+    echo "Attribute check failed" >&2
+    exit $rc
+fi
+
+echo "Check combined page map with one file missing"
+./checkattr "$dumpfile.3" "$dumpfile.1" <<EOF
+file.pagemap = bitmap: 0x1a
+EOF
+rc=$?
+if [ $rc -ne 0 ]; then
+    echo "Attribute check failed" >&2
+    exit $rc
+fi
