tests: Create diskdump v6 binary files from data files
There are several issue with raw binary files:

- There is no place for comments.
- It's difficult to edit them if needed.
- Even more difficult to send patches.

Instead, provide a simple mkbinary helper, which can produce an arbitrary
binary file from a source data file, and convert the binary sample files to
commented source form.

Signed-off-by: Petr Tesarik <petr@tesarici.cz>

diff --git a/tests/diskdump-v6-arm b/tests/diskdump-v6-arm
--- a/tests/diskdump-v6-arm
+++ b/tests/diskdump-v6-arm
@@ -9,9 +9,18 @@
 mkdir -p out || exit 99
 
 name=$( basename "$0" )
-dumpfile="$srcdir/binary/${name}"
+datafile="$srcdir/${name}.data"
+dumpfile="out/${name}.dump"
 resultfile="out/${name}.result"
 expectfile="$srcdir/basic.expect"
+
+cat "$datafile" "$expectfile" | ./mkbinary "$dumpfile"
+rc=$?
+if [ $rc -ne 0 ]; then
+    echo "Cannot create DISKDUMP file" >&2
+    exit $rc
+fi
+echo "Created DISKDUMP: $dumpfile"
 
 ./checkattr "$dumpfile" <<EOF
 max_pfn = number: 1
