Update the PRSTATUS attribute if register value is modified
It is OK to set the attribute value for cpu.<num>.reg.<reg>. But
such changes are not reflected in the PRSTATUS blob attribute.
Add a post-set hook for that purpose.

Note that the hook does not update anything if the new value is
flagged as invalid. If you remove this check, setting the
initial (invalid) value for all register attributes will zero out
PRSTATUS.

Oh, and add a test for the new behaviour.

Signed-off-by: Petr Tesarik <ptesarik@suse.com>

diff --git a/tests/elf-prstatus-x86_64 b/tests/elf-prstatus-x86_64
--- a/tests/elf-prstatus-x86_64
+++ b/tests/elf-prstatus-x86_64
@@ -68,4 +68,11 @@ if [ $rc -ne 0 ]; then
     exit $rc
 fi
 
+./elf-prstatus-mod-x86_64 "$dumpfile"
+rc=$?
+if [ $rc -ne 0 ]; then
+    echo "Attribute modification check failed" >&2
+    exit $rc
+fi
+
 exit 0
