LKCD: Allow gaps in PFN blocks
It is common that only a few pages are missing from an otherwise
continuous PFN block. The current code will allocate a separate block
in that case, but that is suboptimal:

  1. The PFN block chain grows, slowing down lookup.
  2. Each PFN block header occupies some space, so it is even less
     efficient for memory requirements.

Instead, let's use a special value to mark that the PFN is missing
(is a "gap"). I can use zero, because it corresponds to the first
PFN in the block, which is not stored (thanks to commit 0b4f233f1ceb).

Before this commit, the most common length of a PFN block chain is
between 200 and 250. After this commit, almost 70% chains are shorter
than 10 links.

Note that gaps may be filled by pages found later in the dump file.
However, since only 32 bits of the offset are stored in the offs
array (to conserve memory), it may happen that the offset cannot be
represented. In that case, the existing PFN block must be split into
two and a new PFN block must be inserted in the middle. The
lkcd-unordered-faroff test has been extended to check that the
split is done correctly.

Also, the lookup function had to be adjusted, so that it can find
blocks that can be extended up to the current PFN while searching
the dump file for pages.

Signed-off-by: Petr Tesarik <ptesarik@suse.com>

diff --git a/tests/lkcd-unordered-faroff b/tests/lkcd-unordered-faroff
--- a/tests/lkcd-unordered-faroff
+++ b/tests/lkcd-unordered-faroff
@@ -12,6 +12,7 @@ datafile="out/${name}.data"
 dumpfile="out/${name}.dump"
 
 magic="4E 6F 4D 61 67 69 63 21"
+magic2="21 4D 61 67 69 63 32 21"
 cat >"$datafile" <<EOF
 @0
 00*4096
@@ -19,7 +20,8 @@ cat >"$datafile" <<EOF
 00*4096
 # Gap is here at 0x2000 and 0x3000
 @0x4000
-00*4096
+$magic2
+00*4088
 # These two pages are invalid but never used
 @0x100000000 skip=0xa0000000 raw
 @0x200000000 skip=0xa0000000 raw
@@ -58,6 +60,19 @@ if [ $rc -ne 0 ]; then
 fi
 echo "Data: $result"
 expect=$( echo -ne "00\n$magic" )
+if [ "${result% *}" != "$expect" ] ; then
+    echo "Wrong data found" >&2
+    exit 1
+fi
+
+result=$( ./dumpdata "$dumpfile" 0x3fff 9 )
+rc=$?
+if [ $rc -ne 0 ]; then
+    echo "Cannot read data" >&2
+    exit $rc
+fi
+echo "Data: $result"
+expect=$( echo -ne "00\n$magic2" )
 if [ "${result% *}" != "$expect" ] ; then
     echo "Wrong data found" >&2
     exit 1
